### PR TITLE
feat: integrate pyromod patches

### PR DESCRIPTION
**Pull request by alissonlauffer**
## Description

This PR integrates Pyromod patches into Hydrogram. The code has been reformatted and lined according to the project's style guidelines.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by HitaloM — APPROVED** [review]

**Comment by alissonlauffer** [comment]
I think this should be done now. Just one thing: `Message.wait_for_click` (which exists in pyromod) has a `from_user_id` argument, and it doesn't fallback to `Message.from_user.id` if left unspecified (it should, since we're dealing with the context of a message, and not a chat). I suggest API changes in this direction, but that's up to Cezar.

The style check currently fails because it is being tested against a new version of Ruff, which should be updated at our runtime in a different PR.

**Review by HitaloM — APPROVED** [review]
Everything looks good!

**Comment by usernein** [comment]
> has a from_user_id argument, and it doesn't fallback to Message.from_user.id if left unspecified (it should, since we're dealing with the context of a message, and not a chat)

@alissonlauffer in my opinion, it makes no sense to fallback to `Message.from_user.id`

`Message.wait_for_click` means you are waiting for someone to click an inline button on this message and pyromod will give you the corresponding `CallbackQuery `object.

The `from_user_id` parameter is used to specify that you only want to receive the click if it comes from a specific user. If it falls back to `Message.from_user.id`, this means that you will only accept a click if it comes **from the bot itself** (not a userbot) that sent the message with the inline button, which makes no sense.

If `from_user_id` is None, which is the actual default value, it will accept clicks from anyone. If you want to specify it to be someone, you have to explicitly specify a user or a list of users (with their ids or usernames).

I don't think it's a good choice to implicitly limit the allowed users to be only the bot that sent the keyboard if the user didn't specify anyone in `from_user_id`.

**Review by usernein — APPROVED** [review]
LGTM

**Review by HitaloM — APPROVED** [review]
Very good, thank you my friend

**Pull request merged**
